services:
  db:
    image: mariadb:11
    restart: unless-stopped
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: sigmagoon18
      MYSQL_DATABASE: nrl
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -psigmagoon18 --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "3306:3306"
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: NRLObstacleReporting/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: no
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    name: appnet