services:
  db:
    image: mariadb:11
    restart: unless-stopped
    container_name: db-1
    environment:
      MYSQL_ROOT_PASSWORD: superpass
      MYSQL_DATABASE: nrl
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -psuperpass --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "3306:3306"
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: NRLObstacleReporting/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Overstyrer appsettings.Development.json
      ConnectionStrings__DefaultConnection: server=db-1;port=3306;database=nrl;user=root;password=superpass;
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    name: appnet