// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NRLObstacleReporting.Database;

#nullable disable

namespace NRLObstacleReporting.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251013161622_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NRLObstacleReporting.Database.ObstacleCompleteModel", b =>
                {
                    b.Property<bool>("IsDraft")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GeometryGeoJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ObstacleDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("ObstacleHeightMeter")
                        .HasColumnType("int");

                    b.Property<int>("ObstacleId")
                        .HasColumnType("int");

                    b.Property<bool?>("ObstacleIlluminated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObstacleName")
                        .HasColumnType("longtext");

                    b.HasKey("IsDraft");

                    b.ToTable("ObstacleCompleteModel");
                });
#pragma warning restore 612, 618
        }
    }
}
