// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NRLObstacleReporting.Database;

#nullable disable

namespace NRLObstacleReporting.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NRLObstacleReporting.Database.ObstacleDatamodel", b =>
                {
                    b.Property<int>("ObstacleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ObstacleId"));

                    b.Property<string>("GeometryGeoJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObstacleDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("ObstacleHeightMeter")
                        .HasColumnType("int");

                    b.Property<bool?>("ObstacleIlluminated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObstacleName")
                        .HasColumnType("longtext");

                    b.Property<int>("ObstacleTypeId")
                        .HasColumnType("int");

                    b.HasKey("ObstacleId");

                    b.HasIndex("ObstacleTypeId");

                    b.ToTable("ObstacleDatamodels");
                });

            modelBuilder.Entity("NRLObstacleReporting.Database.ObstacleTypeDatamodel", b =>
                {
                    b.Property<int>("ObstacleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ObstacleTypeId"));

                    b.Property<string>("ObstacleName")
                        .HasColumnType("longtext");

                    b.HasKey("ObstacleTypeId");

                    b.ToTable("ObstacleTypeDatamodels");
                });

            modelBuilder.Entity("NRLObstacleReporting.Database.PilotDatamodel", b =>
                {
                    b.Property<int>("PilotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PilotId"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Organization")
                        .HasColumnType("longtext");

                    b.HasKey("PilotId");

                    b.ToTable("PilotDatamodels");
                });

            modelBuilder.Entity("NRLObstacleReporting.Database.RegistrarDatamodel", b =>
                {
                    b.Property<int>("RegistrarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RegistrarId"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Organization")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.HasKey("RegistrarId");

                    b.ToTable("RegistrarDatamodels");
                });

            modelBuilder.Entity("NRLObstacleReporting.Database.ReportDatamodel", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("Dato")
                        .HasColumnType("date");

                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("ReportId");

                    b.HasIndex("PilotId");

                    b.ToTable("ReportDatamodels");
                });

            modelBuilder.Entity("NRLObstacleReporting.Database.ObstacleDatamodel", b =>
                {
                    b.HasOne("NRLObstacleReporting.Database.ObstacleTypeDatamodel", "ObstacleType")
                        .WithMany()
                        .HasForeignKey("ObstacleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObstacleType");
                });

            modelBuilder.Entity("NRLObstacleReporting.Database.ReportDatamodel", b =>
                {
                    b.HasOne("NRLObstacleReporting.Database.PilotDatamodel", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pilot");
                });
#pragma warning restore 612, 618
        }
    }
}
